// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptmolszvkufathwcfvyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0bW9sc3p2a3VmYXRod2Nmdnl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODMyOTAsImV4cCI6MjA3MDQ1OTI5MH0.dR9Aknq0BGJJ34IHitZiY5Ubs3XL1Eh3QnOKkt7CmfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});