// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbssratqgyvpizaptuzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ic3NyYXRxZ3l2cGl6YXB0dXpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTg3MzYsImV4cCI6MjA3MDMzNDczNn0.jo7x3tStMJeehCF9hiUUrnom4c2M4SIzyF0DmhyiTRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});